### ISSUE TITLE
Iphone 12 not show this component

### ISSUE THREAD

**Issue by unfrikimas** [CodyHouse/cd-testimonial-gallery-changelog#1] opened 2022-08-11 07:23 UTC
Hello, I have been using this component and there are people who have problems displaying it on their iphone.
I did an online test and it does not load the component.

Here you can see a video of the test
https://watch.screencastify.com/v/zLZFzMdY9dZVeaM2Khp5

Thanks for your help

**Comment by claudia-romano** [comment] 2022-08-11 11:39
Hi Carlos, are you experiencing this issue when trying to load our component demo as well?
https://codyhouse.co/app/components/demo/demo-testimonial-gallery

Also, is this a bug you are experiencing on the iphone 12 only? Chrome and Safari? Thanks.

**Comment by unfrikimas** [comment] 2022-08-11 12:16
Hi,

i was checking for a while and i think i was not loading the js file 
right. Everything is resolved.

Sometimes there is a space at the end of the component and it does not 
show the last review card. It's intermittent, but sometimes it happens.

You can see it in this video
https://watch.screencastify.com/v/dlHaI5bwEm2aTFBUbyxX

Thank you very much

**Comment by claudia-romano** [comment] 2022-08-12 11:57
Hi there, could you please explain what the issue is? From the video I can see there are 6 reviews visible, not sure which one is missing. Thanks.

**Comment by unfrikimas** [comment] 2022-10-11 07:19
Hi, no problem for now.

When I see the error I record it and send it to you.

Thanks

**Comment by claudia-romano** [comment] 2023-08-28 14:47
I'm closing this as no additional info was provided. Feel free to reopen it if you are still experiencing the bug. Cheers!

**Closed as completed by claudia-romano** 2023-08-28 14:47 UTC
